spring:
    application:
        name: mp-demo
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql:///mybatis
        username: root
        password: 123123123

mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true
        default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    global-config:
        db-config:
            id-type: auto
            logic-delete-field: flag
            logic-delete-value: 1
            logic-not-delete-value: 0